Repository Ubiquiti-App/UCRM-plugins, pull requests merged in 2018-11, with the labels that each got.

#60 mkt-queue-sync update to 1.1
  plugins.json
  plugins/mkt-queue-sync/main.php
  plugins/mkt-queue-sync/mkt-queue-sync.zip
  plugins/mkt-queue-sync/src/.gitignore
  plugins/mkt-queue-sync/src/Data/PluginData.php
  plugins/mkt-queue-sync/src/Data/UcrmData.php
  plugins/mkt-queue-sync/src/Exception/CurlException.php
  plugins/mkt-queue-sync/src/Importer.php
  plugins/mkt-queue-sync/src/Service/CurlExecutor.php
  plugins/mkt-queue-sync/src/Service/FioCurlExecutor.php
  plugins/mkt-queue-sync/src/Service/Logger.php
  plugins/mkt-queue-sync/src/Service/OptionsManager.php
  plugins/mkt-queue-sync/src/Service/UcrmApi.php
  plugins/mkt-queue-sync/src/manifest.json
  plugins/mkt-queue-sync/src/routeros_api.class.php
  plugins/mkt-queue-sync/src/src/Data/PluginData.php
  plugins/mkt-queue-sync/src/src/Synchronizer.php
Labels: ready to merge

#61 Update pack.sh
  plugins/pack-plugin.sh
Labels: enhancement

#65 revenue report plugin UI update
  plugins/revenue-report/revenue-report.zip
  plugins/revenue-report/src/assets/main.css
  plugins/revenue-report/src/composer.lock
  plugins/revenue-report/src/public.php
  plugins/revenue-report/src/templates/form.php
  plugins/revenue-report/src/templates/result.php
Labels: ready to merge

#66 Local api requests
  plugins.json
  plugins/fio_cz/src/composer.json
  plugins/fio_cz/src/manifest.json
  plugins/fio_cz/src/src/Data/UcrmData.php
  plugins/fio_cz/src/src/Service/CurlExecutor.php
  plugins/fio_cz/src/src/Service/UcrmApi.php
  plugins/invoice-csv-export/src/classes/Data/UcrmData.php
  plugins/invoice-csv-export/src/classes/Service/CurlExecutor.php
  plugins/invoice-csv-export/src/classes/Service/UcrmApi.php
  plugins/invoice-csv-export/src/composer.json
  plugins/invoice-csv-export/src/manifest.json
  plugins/kmz-map/src/manifest.json
  plugins/mkt-queue-sync/src/composer.json
  plugins/mkt-queue-sync/src/manifest.json
  plugins/mkt-queue-sync/src/src/Data/PluginData.php
  plugins/mkt-queue-sync/src/src/Data/UcrmData.php
  plugins/mkt-queue-sync/src/src/Service/CurlExecutor.php
  plugins/mkt-queue-sync/src/src/Service/UcrmApi.php
  plugins/packetlogic-packet-manager/src/manifest.json
  plugins/packetlogic-packet-manager/src/src/ucrmInfo.py
  plugins/quickbooks-online/src/composer.json
  plugins/quickbooks-online/src/manifest.json
  plugins/quickbooks-online/src/src/Data/UcrmData.php
  plugins/quickbooks-online/src/src/Service/CurlExecutor.php
  plugins/quickbooks-online/src/src/Service/UcrmApi.php
  plugins/revenue-report/src/classes/Data/UcrmData.php
  plugins/revenue-report/src/classes/Service/CurlExecutor.php
  plugins/revenue-report/src/classes/Service/UcrmApi.php
  plugins/revenue-report/src/composer.json
  plugins/revenue-report/src/manifest.json
  plugins/routeros-packet-manager/src/manifest.json
  plugins/routeros-packet-manager/src/src/ucrmInfo.php
  plugins/sms-twilio/src/composer.json
  plugins/sms-twilio/src/manifest.json
  plugins/sms-twilio/src/src/Data/UcrmData.php
  plugins/sms-twilio/src/src/Service/CurlExecutor.php
  plugins/sms-twilio/src/src/Service/UcrmApi.php
  plugins/ucrm-client-signup/src/composer.json
  plugins/ucrm-client-signup/src/manifest.json
  plugins/ucrm-client-signup/src/src/UCS/UcrmApi.php
  plugins/ucrm-client-signup/src/src/initialize.php
Labels: enhancement

#73 [2.14] public directory docs
  docs/file-structure.md
Labels: UCRM 2.14

#78 Sms twilio - new events
  plugins.json
  plugins/sms-twilio/sms-twilio.zip
  plugins/sms-twilio/src/manifest.json
  plugins/sms-twilio/src/src/Factory/MessageTextFactory.php
Labels: ready to merge

#79 Implement pack-plugin.php
  pack-plugin.php
  plugins/pack-plugin.sh
Labels: enhancement, ready to merge

#83 example usage of "public" directory + better docs
  docs/file-structure.md
  plugins.json
  plugins/invoice-csv-export/invoice-csv-export.zip
  plugins/invoice-csv-export/src/manifest.json
  plugins/invoice-csv-export/src/public/main.css
  plugins/invoice-csv-export/src/templates/form.php
  plugins/revenue-report/revenue-report.zip
  plugins/revenue-report/src/manifest.json
  plugins/revenue-report/src/public/main.css
  plugins/revenue-report/src/templates/form.php
Labels: enhancement

#81 ZIP validation
  generate-json.php
  plugins.json
  plugins/kmz-map/kmz-map.zip
  plugins/mkt-queue-sync/mkt-queue-sync.zip
  plugins/mkt-queue-sync/src/manifest.json
  plugins/packetlogic-packet-manager/packetlogic-packet-manager.zip
  plugins/routeros-packet-manager/routeros-packet-manager.zip
  plugins/routeros-packet-manager/src/manifest.json
  plugins/routeros-packet-manager/src/src/routeros_api_class.php
  plugins/ucrm-client-signup/src/manifest.json
  plugins/ucrm-client-signup/ucrm-client-signup.zip
  validate.php
Labels: enhancement, ready to merge

#85 use UCRM Plugin SDK in "revenue report" and "invoice CSV export" plugins
  plugins.json
  plugins/invoice-csv-export/README.md
  plugins/invoice-csv-export/invoice-csv-export.zip
  plugins/invoice-csv-export/src/classes/Data/PluginData.php
  plugins/invoice-csv-export/src/classes/Data/UcrmData.php
  plugins/invoice-csv-export/src/classes/Data/UcrmUser.php
  plugins/invoice-csv-export/src/classes/Exception/CurlException.php
  plugins/invoice-csv-export/src/classes/Service/CurlExecutor.php
  plugins/invoice-csv-export/src/classes/Service/OptionsManager.php
  plugins/invoice-csv-export/src/classes/Service/UcrmApi.php
  plugins/invoice-csv-export/src/composer.json
  plugins/invoice-csv-export/src/composer.lock
  plugins/invoice-csv-export/src/manifest.json
  plugins/invoice-csv-export/src/public.php
  plugins/revenue-report/README.md
  plugins/revenue-report/revenue-report.zip
  plugins/revenue-report/src/classes/Data/PluginData.php
  plugins/revenue-report/src/classes/Data/UcrmData.php
  plugins/revenue-report/src/classes/Data/UcrmUser.php
  plugins/revenue-report/src/classes/Exception/CurlException.php
  plugins/revenue-report/src/classes/Service/CurlExecutor.php
  plugins/revenue-report/src/classes/Service/OptionsManager.php
  plugins/revenue-report/src/classes/Service/UcrmApi.php
  plugins/revenue-report/src/composer.json
  plugins/revenue-report/src/composer.lock
  plugins/revenue-report/src/manifest.json
  plugins/revenue-report/src/public.php
Labels: ready to merge

#86 plugin SDK link in docs, use SDK in plugin template
  docs/index.md
  examples/plugin-template/plugin-template.zip
  examples/plugin-template/src/.gitignore
  examples/plugin-template/src/composer.json
  examples/plugin-template/src/composer.lock
  examples/plugin-template/src/main.php
  examples/plugin-template/src/manifest.json
  examples/plugin-template/src/public.php
  examples/plugin-template/src/src/Logger.php
  pack-plugin.php
Labels: ready to merge

#87 first plugin tutorial
  docs/index.md
  docs/manifest.md
  docs/tutorials/first-plugin.md
  docs/tutorials/first-plugin/.gitignore
  docs/tutorials/first-plugin/skeleton.zip
  docs/tutorials/first-plugin/skeleton/README.md
  docs/tutorials/first-plugin/skeleton/src/.gitignore
  docs/tutorials/first-plugin/skeleton/src/composer.json
  docs/tutorials/first-plugin/skeleton/src/main.php
  docs/tutorials/first-plugin/skeleton/src/manifest.json
Labels: ready to merge
